### ISSUE TITLE
no firmware image?

### ISSUE THREAD

**Issue by annuvin** [jim11662418/8080_SBC#1]
i'm on the fence about making this, the hardware would be easy to assemble but without a rom image to run i'm not sure what to do with it. could you upload the rom image you used?

**Comment by jim11662418** [comment]
You produce a rom image by assembling the source code with the Macro Assembler AS. Nonetheless, I've added both binary and hex image files to the repository.

**Comment by jim11662418** [comment]
You produce an ROM image by assembling the source code with the Macro
Assembler AS. Nonetheless, I've added both binary and hex images to the
repository.
