### ISSUE TITLE
error on schematic re: atf16v8

### ISSUE THREAD

**Issue by annuvin** [jim11662418/8080_SBC#2]
pin 1 of the atf16v8 says it is connected to pin 1 of the 8224 however the logic file says it is connected to pin 2. that took me a bit to figure out :/ btw i made this in a few days and finally got it to work after scratching my head and triple checking my wiring.

**Comment by jim11662418** [comment]
Corrected. Thanks.

**Comment by annuvin** [comment]
thank you for such a cool project, this was my first DIY single board computer and i didn't have any wire wrap tools or sockets so i used point to point soldering. what an adventure that was.

**Comment by jim11662418** [comment]
I'll correct it. Thanks
