### ISSUE TITLE
possible to replace 4k basic with VTL-2?

### ISSUE THREAD

**Issue by annuvin** [jim11662418/8080_SBC#3]
I had wondered if it would be possible to run VTL-2 on this sbc, the rom looks pretty full already. perhaps it would be possible to replace the 4k basic with VTL-2? sorry to clutter your issues area with this, i know it's not really an issue with the code, just an inquiry. thanks!

**Comment by jim11662418** [comment]
Sorry, can't comment. I don't know what VTL-2 is. Try it and see.
